pipeline {
	agent { label 'Master' }
  
  triggers {
        pollSCM '* * * * *'
  }

  tools {
    maven 'Maven' 
  }
  stages {
    stage ('Build') {
      steps {
        sh '''
        	cd ./Maven/simple-war 
          cat ./src/main/webapp/index.jsp
        	mvn clean package
        	cd ./target/
        	ls
           '''
      }
    }
    
  }

  // post { 
  //     always { 
  //         cleanWs()
  //     }
  // }

}
